{
 "title": "Sangue Doce - API Local",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Últimos logs da API",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{stack=\"sangue-doce\", service=\"sangue-doce-api\"}"
    }
   ]
  },
  {
   "title": "Health checks nos últimos 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({stack=\"sangue-doce\", service=\"sangue-doce-api\"} |= \"/health\" [5m])"
    }
   ]
  },
  {
   "title": "Logs de health",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{stack=\"sangue-doce\", service=\"sangue-doce-api\"} |= \"/health\""
    }
   ]
  },
  {
   "title": "Logs nos últimos 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({stack=\"sangue-doce\", service=\"sangue-doce-api\"}[5m])"
    }
   ]
  },
  {
   "title": "Heap usado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sangue_doce_nodejs_heap_size_used_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU da API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(sangue_doce_process_cpu_user_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória da API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sangue_doce_process_resident_memory_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Api On Line",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "up{job=\"sangue-doce-api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}