FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache openssl \
  && npm install -g @infisical/cli \
  && corepack enable

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

EXPOSE 3011

CMD ["yarn", "start:dev"]
