const { sensorPostContent } = require('./post-content');

const seedPosts = [
  {
    slug: 'nova-fase-dos-sensores',
    title: 'Nova fase dos sensores: leitura continua vira aliada da autonomia',
    excerpt:
      'Monitores continuos sairam do hospital e entraram na rotina. Entenda como a leitura em tempo real muda decisoes sobre comida, movimento e descanso.',
    standfirst:
      'Monitores continuos sairam do hospital e entraram na rotina. Entenda como a leitura em tempo real muda decisoes sobre comida, movimento e descanso, sem transformar o dia em planilha.',
    categorySlug: 'cuidado-diario',
    authorSlug: 'helena-marques',
    tagSlugs: ['glicemia', 'monitoramento', 'tecnologia', 'rotina', 'autonomia'],
    readingMinutes: 8,
    coverImageUrl: '/images/sensor.png',
    verticalImageUrl: '/images/sensor.png',
    coverImageAlt: 'Pessoa usando sensor de glicose no braco em uma rotina domestica',
    coverCaption:
      'Sensores de leitura continua passaram a fazer parte da rotina, com dados acessiveis pelo celular.',
    publishedAt: '2026-06-21T09:00:00.000Z',
    featured: true,
    content: sensorPostContent,
  },
  {
    slug: 'prato-equilibrado-sem-contagem-complicada',
    title: 'Prato equilibrado sem contagem complicada',
    excerpt: 'Um metodo visual para montar refeicoes que sustentam a glicemia.',
    categorySlug: 'alimentacao',
    authorSlug: 'helena-marques',
    tagSlugs: ['alimentacao', 'glicemia', 'rotina'],
    readingMinutes: 5,
    coverImageUrl: '/original-project/screenshots/02-scan.png',
    verticalImageUrl: '/images/comida_saudavel_vertical.png',
    coverImageAlt: 'Prato colorido e equilibrado visto de cima',
    publishedAt: '2026-06-20T09:00:00.000Z',
  },
  {
    slug: 'sono-irregular-pode-afetar-a-resistencia-a-insulina',
    title: 'Sono irregular pode afetar a resistencia a insulina',
    excerpt: 'O que a ciencia do sono diz sobre noites curtas e picos de acucar.',
    categorySlug: 'prevencao',
    authorSlug: 'helena-marques',
    tagSlugs: ['sono', 'prevencao', 'glicemia'],
    readingMinutes: 6,
    coverImageUrl: '/original-project/screenshots/03-scan.png',
    verticalImageUrl: '/images/comida_saudavel_vertical.png',
    coverImageAlt: 'Quarto tranquilo com luz suave de manha',
    publishedAt: '2026-06-19T09:00:00.000Z',
  },
  {
    slug: 'como-organizar-as-leituras-da-semana',
    title: 'Como organizar as leituras da semana sem complicar a rotina',
    excerpt:
      'Um guia pratico para registrar horarios, contexto e sintomas sem transformar o cuidado em tarefa pesada.',
    categorySlug: 'rotina',
    authorSlug: 'jander-nery',
    tagSlugs: ['rotina', 'monitoramento', 'glicemia'],
    readingMinutes: 7,
    coverImageUrl: '/images/sensor_vertical.png',
    verticalImageUrl: '/images/sensor_vertical.png',
    coverImageAlt: 'Pessoa consultando leituras de glicose no celular',
    publishedAt: '2026-06-18T09:00:00.000Z',
  },
  {
    slug: 'cafe-da-manha-e-glicemia',
    title: 'Cafe da manha e glicemia: ajustes pequenos que ajudam',
    excerpt:
      'Combinar fibras, proteinas e escolhas simples pode reduzir picos logo nas primeiras horas do dia.',
    categorySlug: 'alimentacao',
    authorSlug: 'helena-marques',
    tagSlugs: ['alimentacao', 'glicemia', 'rotina'],
    readingMinutes: 5,
    coverImageUrl: '/images/comida_saudavel.png',
    verticalImageUrl: '/images/comida_saudavel_vertical.png',
    coverImageAlt: 'Cafe da manha com alimentos variados e equilibrados',
    publishedAt: '2026-06-17T09:00:00.000Z',
  },
  {
    slug: 'quando-conversar-com-a-equipe-de-saude',
    title: 'Quando conversar com a equipe de saude sobre variacoes recentes',
    excerpt:
      'Alguns sinais merecem ser levados para consulta com historico, horarios e observacoes bem organizados.',
    categorySlug: 'consulta',
    authorSlug: 'helena-marques',
    tagSlugs: ['consulta', 'monitoramento', 'seguranca'],
    readingMinutes: 8,
    coverImageUrl: '/antes_da_consulta.png',
    verticalImageUrl: '/antes_da_consulta.png',
    coverImageAlt: 'Pessoa organizando anotacoes antes de uma consulta',
    publishedAt: '2026-06-16T09:00:00.000Z',
  },
  {
    slug: 'mercado-sem-pressa-lendo-rotulos',
    title: 'Mercado sem pressa: lendo rotulos de carboidratos',
    excerpt:
      'Carboidratos totais, acucares adicionados e fibras contam uma historia melhor quando vistos juntos.',
    categorySlug: 'compras',
    authorSlug: 'jander-nery',
    tagSlugs: ['compras', 'alimentacao', 'glicemia'],
    readingMinutes: 6,
    coverImageUrl: '/no_mercado.png',
    verticalImageUrl: '/no_mercado.png',
    coverImageAlt: 'Pessoa lendo rotulo nutricional no mercado',
    publishedAt: '2026-06-14T09:00:00.000Z',
  },
  {
    slug: 'exercicio-no-fim-do-dia',
    title: 'Exercicio no fim do dia: o que observar antes de dormir',
    excerpt:
      'Treinos podem impactar a glicose por horas. Veja sinais que ajudam a planejar recuperacao e descanso.',
    categorySlug: 'movimento',
    authorSlug: 'helena-marques',
    tagSlugs: ['movimento', 'glicemia', 'sono'],
    readingMinutes: 7,
    coverImageUrl: '/depois_do_exercicio.png',
    verticalImageUrl: '/depois_do_exercicio.png',
    coverImageAlt: 'Pessoa descansando depois de exercicio fisico',
    publishedAt: '2026-06-13T09:00:00.000Z',
  },
  {
    slug: 'tecnologia-no-cuidado',
    title: 'Tecnologia no cuidado: dados bons ainda precisam de contexto',
    excerpt:
      'Sensores e diarios ficam mais uteis quando cada leitura vem acompanhada de refeicao, sono e movimento.',
    categorySlug: 'tecnologia',
    authorSlug: 'jander-nery',
    tagSlugs: ['tecnologia', 'monitoramento', 'rotina'],
    readingMinutes: 9,
    coverImageUrl: '/images/sensor.png',
    verticalImageUrl: '/images/sensor_vertical.png',
    coverImageAlt: 'Aplicativo de saude exibindo dados de glicose',
    publishedAt: '2026-06-07T09:00:00.000Z',
  },
  {
    slug: 'lanches-entre-refeicoes',
    title: 'Lanches entre refeicoes: como evitar decisoes no improviso',
    excerpt:
      'Ter opcoes simples por perto ajuda a atravessar intervalos maiores com mais previsibilidade.',
    categorySlug: 'alimentacao',
    authorSlug: 'helena-marques',
    tagSlugs: ['alimentacao', 'rotina', 'glicemia'],
    readingMinutes: 4,
    coverImageUrl: '/images/comida_saudavel_vertical.png',
    verticalImageUrl: '/images/comida_saudavel_vertical.png',
    coverImageAlt: 'Lanches simples organizados para a semana',
    publishedAt: '2026-06-06T09:00:00.000Z',
  },
  {
    slug: 'sinais-de-alerta',
    title: 'Sinais de alerta que nao devem ficar so na memoria',
    excerpt:
      'Tontura, tremores e confusao merecem registro com horario e leitura para orientar proximas decisoes.',
    categorySlug: 'seguranca',
    authorSlug: 'jander-nery',
    tagSlugs: ['seguranca', 'monitoramento', 'consulta'],
    readingMinutes: 6,
    coverImageUrl: '/images/saudavel.png',
    verticalImageUrl: '/images/saudavel.png',
    coverImageAlt: 'Pessoa registrando sintomas e leituras de saude',
    publishedAt: '2026-05-31T09:00:00.000Z',
  },
];

module.exports = {
  seedPosts,
};
